name: ci
permissions:
  contents: read
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04, macos-14, macos-15 ]
        rust:
          - stable
          - beta
          - nightly
          - 1.74.0  # MSRV
    steps:
      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal
          rustup override set ${{ matrix.rust }}
      - uses: actions/checkout@v4
      - run: cargo check -v
      - run: cargo test -v

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust stable
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
      - uses: actions/checkout@v4
      - run: cargo clippy -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust stable
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check
